name: Build source

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "dfc/**"
      - "app/**"
      - ".github/workflows/build.yml"
      - "*.gradle"
      - "gradle/**"
      - "gradle.properties"
  push:
    branches: [ master ]
    paths:
      - "dfc/**"
      - "app/**"
      - ".github/workflows/build.yml"
      - "*.gradle"
      - "gradle/**"
      - "gradle.properties"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Build project
        run: ./gradlew :dfc:assemble :dfc:assembleDebugAndroidTest :app:assembleDebug
