name: Build source

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - ".github/workflows/build.yml"
      - "*.gradle"
      - "gradle.properties"
      - "gradle/**"
      - "app/**"
      - "dfc/**"
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/build.yml"
      - "*.gradle"
      - "gradle.properties"
      - "gradle/**"
      - "app/**"
      - "dfc/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Build
        run: ./gradlew :dfc:assemble :dfc:testDebugUnitTest :app:assembleDebug
